version: '3.8'

x-postgres-common:
  &postgres-common
  network_mode: "host"
  image: postgres:DEVOPS_IMAGE_TAG
  user: postgres
  restart: always
  healthcheck:
    test: 'pg_isready -U user --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5

services:
  postgres_replica:
    <<: *postgres-common
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
    command: |
      bash -c "
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot_DEVOPS_INDEX --host=DEVOPS_PRIMARY_IP --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres -c max_connections=DEVOPS_MAX_CONNECTIONS  -c shared_buffers=DEVOPS_SHARED_BUFF -c primary_slot_name=replication_slot_DEVOPS_INDEX
      "